In [24]:
import pandas as pd
import numpy as np

data = {'let': ['a', 'b', 'c', 'd'],
        'num': [1, 2, 3, 4]}

df = pd.DataFrame(data)

# create col 'test' with 0:
df['test'] = 0

# using .eq(1) to check 'num' column, and return its content to 'test' column or 0 if not:
df['test'] = df[df['num'].eq(1)]['num'] | 0


# change NaN to 0:
df['test'] = df['test'].fillna(0)

print(df)

  let  num  test
0   a    1   1.0
1   b    2   0.0
2   c    3   0.0
3   d    4   0.0

In [ ]:
# for learning purposes:
df = pd.DataFrame({'col':[
    1,2,np.NaN, np.NaN, np.NaN, 6,7,8,9,10,np.NaN,np.NaN,13,14
]})

df['cumsum'] = df['col'].isnull().astype(int).groupby(df['col'].notnull().astype(int).cumsum()).cumsum()

print(df)

In [25]:
miss_df = pd.DataFrame({"values": [1,0,2,2,0,0,3,3,3,0,0,0,4,4,4,4,0,0,0,0,5,5,5,5,5,0,0,0,0,0,6,6,6,6,6,6,0,0,0,0,0,0]})

print(miss_df)

    values
0        1
1        0
2        2
3        2
4        0
5        0
6        3
7        3
8        3
9        0
10       0
11       0
12       4
13       4
14       4
15       4
16       0
17       0
18       0
19       0
20       5
21       5
22       5
23       5
24       5
25       0
26       0
27       0
28       0
29       0
30       6
31       6
32       6
33       6
34       6
35       6
36       0
37       0
38       0
39       0
40       0
41       0

In [34]:
# create col 'inv_bool' to store integer version of negation of boolean of column 'values':
miss_df['inv_bool'] = (~miss_df['values'].astype(bool)).astype(int)

# fill 0 with NaN:
miss_df['inv_bool'] = miss_df['inv_bool'].replace(0, np.nan)

# check:
print(miss_df)

    values  inv_bool  cumsum
0        1       NaN       0
1        0       1.0       0
2        2       NaN       0
3        2       NaN       0
4        0       1.0       0
5        0       1.0       0
6        3       NaN       0
7        3       NaN       0
8        3       NaN       0
9        0       1.0       0
10       0       1.0       0
11       0       1.0       0
12       4       NaN       0
13       4       NaN       0
14       4       NaN       0
15       4       NaN       0
16       0       1.0       0
17       0       1.0       0
18       0       1.0       0
19       0       1.0       0
20       5       NaN       0
21       5       NaN       0
22       5       NaN       0
23       5       NaN       0
24       5       NaN       0
25       0       1.0       0
26       0       1.0       0
27       0       1.0       0
28       0       1.0       0
29       0       1.0       0
30       6       NaN       0
31       6       NaN       0
32       6       NaN       0
33       6       NaN       0
34       6       NaN       0
35       6       NaN       0
36       0       1.0       0
37       0       1.0       0
38       0       1.0       0
39       0       1.0       0
40       0       1.0       0
41       0       1.0       0

In [35]:
# get local cumsum of 'inv_bool' column:
miss_df['cumsum'] = miss_df['inv_bool'].isnull().astype(int).groupby(miss_df['inv_bool'].notnull().astype(int).cumsum()).cumsum()

# check:
print(miss_df)

    values  inv_bool  cumsum
0        1       NaN       1
1        0       1.0       0
2        2       NaN       1
3        2       NaN       2
4        0       1.0       0
5        0       1.0       0
6        3       NaN       1
7        3       NaN       2
8        3       NaN       3
9        0       1.0       0
10       0       1.0       0
11       0       1.0       0
12       4       NaN       1
13       4       NaN       2
14       4       NaN       3
15       4       NaN       4
16       0       1.0       0
17       0       1.0       0
18       0       1.0       0
19       0       1.0       0
20       5       NaN       1
21       5       NaN       2
22       5       NaN       3
23       5       NaN       4
24       5       NaN       5
25       0       1.0       0
26       0       1.0       0
27       0       1.0       0
28       0       1.0       0
29       0       1.0       0
30       6       NaN       1
31       6       NaN       2
32       6       NaN       3
33       6       NaN       4
34       6       NaN       5
35       6       NaN       6
36       0       1.0       0
37       0       1.0       0
38       0       1.0       0
39       0       1.0       0
40       0       1.0       0
41       0       1.0       0

In [40]:
# create col 'plus' with values from 'cumsum' added by 0.1 skiping 0s:
miss_df['plus'] = miss_df['cumsum'].where(miss_df['cumsum'] != 0, np.NaN) + 0.1

# fill NaN with 0s:
miss_df['plus'] = miss_df['plus'].fillna(0)

# check:
print(miss_df)

    values  inv_bool  cumsum  plus
0        1       NaN       1   1.1
1        0       1.0       0   0.0
2        2       NaN       1   1.1
3        2       NaN       2   2.1
4        0       1.0       0   0.0
5        0       1.0       0   0.0
6        3       NaN       1   1.1
7        3       NaN       2   2.1
8        3       NaN       3   3.1
9        0       1.0       0   0.0
10       0       1.0       0   0.0
11       0       1.0       0   0.0
12       4       NaN       1   1.1
13       4       NaN       2   2.1
14       4       NaN       3   3.1
15       4       NaN       4   4.1
16       0       1.0       0   0.0
17       0       1.0       0   0.0
18       0       1.0       0   0.0
19       0       1.0       0   0.0
20       5       NaN       1   1.1
21       5       NaN       2   2.1
22       5       NaN       3   3.1
23       5       NaN       4   4.1
24       5       NaN       5   5.1
25       0       1.0       0   0.0
26       0       1.0       0   0.0
27       0       1.0       0   0.0
28       0       1.0       0   0.0
29       0       1.0       0   0.0
30       6       NaN       1   1.1
31       6       NaN       2   2.1
32       6       NaN       3   3.1
33       6       NaN       4   4.1
34       6       NaN       5   5.1
35       6       NaN       6   6.1
36       0       1.0       0   0.0
37       0       1.0       0   0.0
38       0       1.0       0   0.0
39       0       1.0       0   0.0
40       0       1.0       0   0.0
41       0       1.0       0   0.0

In [50]:
# get diff of 'plus' column shifted one row up:
miss_df['diff_up'] = miss_df['plus'].diff().shift(-1)

# check:
print(miss_df)

    values  inv_bool  cumsum  plus  diff_up
0        1       NaN       1   1.1     -1.1
1        0       1.0       0   0.0      1.1
2        2       NaN       1   1.1      1.0
3        2       NaN       2   2.1     -2.1
4        0       1.0       0   0.0      0.0
5        0       1.0       0   0.0      1.1
6        3       NaN       1   1.1      1.0
7        3       NaN       2   2.1      1.0
8        3       NaN       3   3.1     -3.1
9        0       1.0       0   0.0      0.0
10       0       1.0       0   0.0      0.0
11       0       1.0       0   0.0      1.1
12       4       NaN       1   1.1      1.0
13       4       NaN       2   2.1      1.0
14       4       NaN       3   3.1      1.0
15       4       NaN       4   4.1     -4.1
16       0       1.0       0   0.0      0.0
17       0       1.0       0   0.0      0.0
18       0       1.0       0   0.0      0.0
19       0       1.0       0   0.0      1.1
20       5       NaN       1   1.1      1.0
21       5       NaN       2   2.1      1.0
22       5       NaN       3   3.1      1.0
23       5       NaN       4   4.1      1.0
24       5       NaN       5   5.1     -5.1
25       0       1.0       0   0.0      0.0
26       0       1.0       0   0.0      0.0
27       0       1.0       0   0.0      0.0
28       0       1.0       0   0.0      0.0
29       0       1.0       0   0.0      1.1
30       6       NaN       1   1.1      1.0
31       6       NaN       2   2.1      1.0
32       6       NaN       3   3.1      1.0
33       6       NaN       4   4.1      1.0
34       6       NaN       5   5.1      1.0
35       6       NaN       6   6.1     -6.1
36       0       1.0       0   0.0      0.0
37       0       1.0       0   0.0      0.0
38       0       1.0       0   0.0      0.0
39       0       1.0       0   0.0      0.0
40       0       1.0       0   0.0      0.0
41       0       1.0       0   0.0      NaN

In [62]:
# create col 'end' with index value if .lt(-1.1):
miss_df['end'] = miss_df[miss_df['diff_up'].lt(-1.1)]['diff_up']

# fill NaN with 0s for col 'end':
miss_df['end'] = miss_df['end'].fillna(0)

# check:
print(miss_df)

    index  values  inv_bool  cumsum  plus  diff_up  end
0       0       1       NaN       1   1.1     -1.1  0.0
1       1       0       1.0       0   0.0      1.1  0.0
2       2       2       NaN       1   1.1      1.0  0.0
3       3       2       NaN       2   2.1     -2.1 -2.1
4       4       0       1.0       0   0.0      0.0  0.0
5       5       0       1.0       0   0.0      1.1  0.0
6       6       3       NaN       1   1.1      1.0  0.0
7       7       3       NaN       2   2.1      1.0  0.0
8       8       3       NaN       3   3.1     -3.1 -3.1
9       9       0       1.0       0   0.0      0.0  0.0
10     10       0       1.0       0   0.0      0.0  0.0
11     11       0       1.0       0   0.0      1.1  0.0
12     12       4       NaN       1   1.1      1.0  0.0
13     13       4       NaN       2   2.1      1.0  0.0
14     14       4       NaN       3   3.1      1.0  0.0
15     15       4       NaN       4   4.1     -4.1 -4.1
16     16       0       1.0       0   0.0      0.0  0.0
17     17       0       1.0       0   0.0      0.0  0.0
18     18       0       1.0       0   0.0      0.0  0.0
19     19       0       1.0       0   0.0      1.1  0.0
20     20       5       NaN       1   1.1      1.0  0.0
21     21       5       NaN       2   2.1      1.0  0.0
22     22       5       NaN       3   3.1      1.0  0.0
23     23       5       NaN       4   4.1      1.0  0.0
24     24       5       NaN       5   5.1     -5.1 -5.1
25     25       0       1.0       0   0.0      0.0  0.0
26     26       0       1.0       0   0.0      0.0  0.0
27     27       0       1.0       0   0.0      0.0  0.0
28     28       0       1.0       0   0.0      0.0  0.0
29     29       0       1.0       0   0.0      1.1  0.0
30     30       6       NaN       1   1.1      1.0  0.0
31     31       6       NaN       2   2.1      1.0  0.0
32     32       6       NaN       3   3.1      1.0  0.0
33     33       6       NaN       4   4.1      1.0  0.0
34     34       6       NaN       5   5.1      1.0  0.0
35     35       6       NaN       6   6.1     -6.1 -6.1
36     36       0       1.0       0   0.0      0.0  0.0
37     37       0       1.0       0   0.0      0.0  0.0
38     38       0       1.0       0   0.0      0.0  0.0
39     39       0       1.0       0   0.0      0.0  0.0
40     40       0       1.0       0   0.0      0.0  0.0
41     41       0       1.0       0   0.0      NaN  0.0

In [64]:
# create 'index' column as first column with index values:
try:
    miss_df.insert(0, 'index', miss_df.index)
except:
    pass

# check:
print(miss_df)

    index  values  inv_bool  cumsum  plus  diff_up  end
0       0       1       NaN       1   1.1     -1.1  0.0
1       1       0       1.0       0   0.0      1.1  0.0
2       2       2       NaN       1   1.1      1.0  0.0
3       3       2       NaN       2   2.1     -2.1 -2.1
4       4       0       1.0       0   0.0      0.0  0.0
5       5       0       1.0       0   0.0      1.1  0.0
6       6       3       NaN       1   1.1      1.0  0.0
7       7       3       NaN       2   2.1      1.0  0.0
8       8       3       NaN       3   3.1     -3.1 -3.1
9       9       0       1.0       0   0.0      0.0  0.0
10     10       0       1.0       0   0.0      0.0  0.0
11     11       0       1.0       0   0.0      1.1  0.0
12     12       4       NaN       1   1.1      1.0  0.0
13     13       4       NaN       2   2.1      1.0  0.0
14     14       4       NaN       3   3.1      1.0  0.0
15     15       4       NaN       4   4.1     -4.1 -4.1
16     16       0       1.0       0   0.0      0.0  0.0
17     17       0       1.0       0   0.0      0.0  0.0
18     18       0       1.0       0   0.0      0.0  0.0
19     19       0       1.0       0   0.0      1.1  0.0
20     20       5       NaN       1   1.1      1.0  0.0
21     21       5       NaN       2   2.1      1.0  0.0
22     22       5       NaN       3   3.1      1.0  0.0
23     23       5       NaN       4   4.1      1.0  0.0
24     24       5       NaN       5   5.1     -5.1 -5.1
25     25       0       1.0       0   0.0      0.0  0.0
26     26       0       1.0       0   0.0      0.0  0.0
27     27       0       1.0       0   0.0      0.0  0.0
28     28       0       1.0       0   0.0      0.0  0.0
29     29       0       1.0       0   0.0      1.1  0.0
30     30       6       NaN       1   1.1      1.0  0.0
31     31       6       NaN       2   2.1      1.0  0.0
32     32       6       NaN       3   3.1      1.0  0.0
33     33       6       NaN       4   4.1      1.0  0.0
34     34       6       NaN       5   5.1      1.0  0.0
35     35       6       NaN       6   6.1     -6.1 -6.1
36     36       0       1.0       0   0.0      0.0  0.0
37     37       0       1.0       0   0.0      0.0  0.0
38     38       0       1.0       0   0.0      0.0  0.0
39     39       0       1.0       0   0.0      0.0  0.0
40     40       0       1.0       0   0.0      0.0  0.0
41     41       0       1.0       0   0.0      NaN  0.0

In [65]:
# create col 'end_index' that use .ne() for NaNs in column 'end' and return index values from 'index' column:
miss_df['end_index'] = miss_df[miss_df['end'].ne(0)]['index']

# check:
print(miss_df)

    index  values  inv_bool  cumsum  plus  diff_up  end  end_index
0       0       1       NaN       1   1.1     -1.1  0.0        NaN
1       1       0       1.0       0   0.0      1.1  0.0        NaN
2       2       2       NaN       1   1.1      1.0  0.0        NaN
3       3       2       NaN       2   2.1     -2.1 -2.1        3.0
4       4       0       1.0       0   0.0      0.0  0.0        NaN
5       5       0       1.0       0   0.0      1.1  0.0        NaN
6       6       3       NaN       1   1.1      1.0  0.0        NaN
7       7       3       NaN       2   2.1      1.0  0.0        NaN
8       8       3       NaN       3   3.1     -3.1 -3.1        8.0
9       9       0       1.0       0   0.0      0.0  0.0        NaN
10     10       0       1.0       0   0.0      0.0  0.0        NaN
11     11       0       1.0       0   0.0      1.1  0.0        NaN
12     12       4       NaN       1   1.1      1.0  0.0        NaN
13     13       4       NaN       2   2.1      1.0  0.0        NaN
14     14       4       NaN       3   3.1      1.0  0.0        NaN
15     15       4       NaN       4   4.1     -4.1 -4.1       15.0
16     16       0       1.0       0   0.0      0.0  0.0        NaN
17     17       0       1.0       0   0.0      0.0  0.0        NaN
18     18       0       1.0       0   0.0      0.0  0.0        NaN
19     19       0       1.0       0   0.0      1.1  0.0        NaN
20     20       5       NaN       1   1.1      1.0  0.0        NaN
21     21       5       NaN       2   2.1      1.0  0.0        NaN
22     22       5       NaN       3   3.1      1.0  0.0        NaN
23     23       5       NaN       4   4.1      1.0  0.0        NaN
24     24       5       NaN       5   5.1     -5.1 -5.1       24.0
25     25       0       1.0       0   0.0      0.0  0.0        NaN
26     26       0       1.0       0   0.0      0.0  0.0        NaN
27     27       0       1.0       0   0.0      0.0  0.0        NaN
28     28       0       1.0       0   0.0      0.0  0.0        NaN
29     29       0       1.0       0   0.0      1.1  0.0        NaN
30     30       6       NaN       1   1.1      1.0  0.0        NaN
31     31       6       NaN       2   2.1      1.0  0.0        NaN
32     32       6       NaN       3   3.1      1.0  0.0        NaN
33     33       6       NaN       4   4.1      1.0  0.0        NaN
34     34       6       NaN       5   5.1      1.0  0.0        NaN
35     35       6       NaN       6   6.1     -6.1 -6.1       35.0
36     36       0       1.0       0   0.0      0.0  0.0        NaN
37     37       0       1.0       0   0.0      0.0  0.0        NaN
38     38       0       1.0       0   0.0      0.0  0.0        NaN
39     39       0       1.0       0   0.0      0.0  0.0        NaN
40     40       0       1.0       0   0.0      0.0  0.0        NaN
41     41       0       1.0       0   0.0      NaN  0.0        NaN

In [71]:
# create col 'diff' with diff for 'plus' column:
miss_df['diff'] = miss_df['plus'].diff()

# create col 'start_index' that use .eq() for 1.1 in column 'diff' and return index values from 'index' column added by 1:
miss_df['start_index'] = miss_df[miss_df['diff'].eq(1.1)]['index']

# check:
print(miss_df)

    index  values  inv_bool  cumsum  plus  diff_up  end  end_index  diff  \
0       0       1       NaN       1   1.1     -1.1  0.0        NaN   NaN
1       1       0       1.0       0   0.0      1.1  0.0        NaN  -1.1
2       2       2       NaN       1   1.1      1.0  0.0        NaN   1.1
3       3       2       NaN       2   2.1     -2.1 -2.1        3.0   1.0
4       4       0       1.0       0   0.0      0.0  0.0        NaN  -2.1
5       5       0       1.0       0   0.0      1.1  0.0        NaN   0.0
6       6       3       NaN       1   1.1      1.0  0.0        NaN   1.1
7       7       3       NaN       2   2.1      1.0  0.0        NaN   1.0
8       8       3       NaN       3   3.1     -3.1 -3.1        8.0   1.0
9       9       0       1.0       0   0.0      0.0  0.0        NaN  -3.1
10     10       0       1.0       0   0.0      0.0  0.0        NaN   0.0
11     11       0       1.0       0   0.0      1.1  0.0        NaN   0.0
12     12       4       NaN       1   1.1      1.0  0.0        NaN   1.1
13     13       4       NaN       2   2.1      1.0  0.0        NaN   1.0
14     14       4       NaN       3   3.1      1.0  0.0        NaN   1.0
15     15       4       NaN       4   4.1     -4.1 -4.1       15.0   1.0
16     16       0       1.0       0   0.0      0.0  0.0        NaN  -4.1
17     17       0       1.0       0   0.0      0.0  0.0        NaN   0.0
18     18       0       1.0       0   0.0      0.0  0.0        NaN   0.0
19     19       0       1.0       0   0.0      1.1  0.0        NaN   0.0
20     20       5       NaN       1   1.1      1.0  0.0        NaN   1.1
21     21       5       NaN       2   2.1      1.0  0.0        NaN   1.0
22     22       5       NaN       3   3.1      1.0  0.0        NaN   1.0
23     23       5       NaN       4   4.1      1.0  0.0        NaN   1.0
24     24       5       NaN       5   5.1     -5.1 -5.1       24.0   1.0
25     25       0       1.0       0   0.0      0.0  0.0        NaN  -5.1
26     26       0       1.0       0   0.0      0.0  0.0        NaN   0.0
27     27       0       1.0       0   0.0      0.0  0.0        NaN   0.0
28     28       0       1.0       0   0.0      0.0  0.0        NaN   0.0
29     29       0       1.0       0   0.0      1.1  0.0        NaN   0.0
30     30       6       NaN       1   1.1      1.0  0.0        NaN   1.1
31     31       6       NaN       2   2.1      1.0  0.0        NaN   1.0
32     32       6       NaN       3   3.1      1.0  0.0        NaN   1.0
33     33       6       NaN       4   4.1      1.0  0.0        NaN   1.0
34     34       6       NaN       5   5.1      1.0  0.0        NaN   1.0
35     35       6       NaN       6   6.1     -6.1 -6.1       35.0   1.0
36     36       0       1.0       0   0.0      0.0  0.0        NaN  -6.1
37     37       0       1.0       0   0.0      0.0  0.0        NaN   0.0
38     38       0       1.0       0   0.0      0.0  0.0        NaN   0.0
39     39       0       1.0       0   0.0      0.0  0.0        NaN   0.0
40     40       0       1.0       0   0.0      0.0  0.0        NaN   0.0
41     41       0       1.0       0   0.0      NaN  0.0        NaN   0.0

    start_index
0           NaN
1           NaN
2           2.0
3           NaN
4           NaN
5           NaN
6           6.0
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12         12.0
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
20         20.0
21          NaN
22          NaN
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
30         30.0
31          NaN
32          NaN
33          NaN
34          NaN
35          NaN
36          NaN
37          NaN
38          NaN
39          NaN
40          NaN
41          NaN

In [79]:
# copy 'start_index' to as df 'start_df':
start_df = miss_df['start_index'].copy()

# delete NaNs from 'start_df':
start_df = start_df.dropna()

# reset index for 'start_df':
start_df = start_df.reset_index(drop=True)

# copy 'end_index' to as df 'end_df':
end_df = miss_df['end_index'].copy()

# delete NaNs from 'end_df':
end_df = end_df.dropna()

# reset index for 'end_df':
end_df = end_df.reset_index(drop=True)

# create df 'missing_data_index_count' with cols 'start_df' and 'end_df':
missing_data_index_count = pd.DataFrame()

missing_data_index_count['start_df'] = start_df
missing_data_index_count['end_df'] = end_df

# create col 'missing_count' with diff of 'end_df' and 'start_df' columns plus 1:
missing_data_index_count['missing_count'] = missing_data_index_count['end_df'] - missing_data_index_count['start_df'] + 1

# check:
print(missing_data_index_count)

   start_df  end_df  missing_count
0       2.0     3.0            2.0
1       6.0     8.0            3.0
2      12.0    15.0            4.0
3      20.0    24.0            5.0
4      30.0    35.0            6.0

In [ ]:
# hard code 'inv_bool' values to create new df 'missing_data':
missing_data = pd.DataFrame({"values": [1,0,1,1,0,0,1,1,1,0,0,0,1,1,1,1,0,0,0,0,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0]})